package com.oayilix.lodestar.api

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.net.Uri

/**
 * Lodestar SDK entry point that loads the compile-time route table and starts route navigation.
 * Lodestar 的运行时入口，负责加载编译期路由表并执行页面导航。
 *
 * Initialization is thread-safe and idempotent; the published route table is immutable.
 * 初始化是线程安全且幂等的；成功后发布的路由表不可变。
 */
object Lodestar {

    private const val GENERATED_MAPPING = "com.oayilix.lodestar.mapping.LodestarMapping"
    private val initializationLock = Any()

    @Volatile
    private var routes: Map<String, Class<out Activity>>? = null

    /** Replaceable logger; silent by default. 可替换的日志出口；默认不输出日志。 */
    @Volatile
    var logger: LodestarLogger = LodestarLogger.NONE

    /**
     * Loads the aggregate route table generated by the Gradle plugin.
     * 加载 Gradle 插件生成的聚合路由表。
     *
     * @return Initialization result; partial routes are never published. 初始化结果；失败不会发布部分路由。
     */
    @JvmStatic
    fun init(): InitializationResult {
        routes?.let { return InitializationResult.AlreadyInitialized(it.size) }

        synchronized(initializationLock) {
            routes?.let { return InitializationResult.AlreadyInitialized(it.size) }
            return try {
                val generatedClass = Class.forName(GENERATED_MAPPING)
                val rawMapping = generatedClass.getMethod("get").invoke(null) as? Map<*, *>
                    ?: error("Generated Lodestar mapping did not return a Map.")
                val verifiedRoutes = LinkedHashMap<String, Class<out Activity>>(rawMapping.size)

                rawMapping.forEach { (route, target) ->
                    require(route is String) { "Generated route key must be a String." }
                    require(target is Class<*> && Activity::class.java.isAssignableFrom(target)) {
                        "Generated route target for '$route' must extend Activity."
                    }
                    @Suppress("UNCHECKED_CAST")
                    verifiedRoutes[route] = target as Class<out Activity>
                }

                val immutableRoutes = verifiedRoutes.toMap()
                routes = immutableRoutes
                logger.info("Initialized ${immutableRoutes.size} Lodestar routes.")
                InitializationResult.Success(immutableRoutes.size)
            } catch (cause: Throwable) {
                logger.error("Failed to initialize Lodestar routes.", cause)
                InitializationResult.Failure(cause)
            }
        }
    }

    /**
     * Initializes Lodestar and throws when the generated mapping cannot be loaded.
     * 初始化 Lodestar；当生成的路由表无法加载时直接抛出异常。
     *
     * This is the concise Application startup API. Use [init] when the app wants to handle
     * initialization failures explicitly.
     * 这是更简洁的 Application 启动 API。当 App 需要显式处理初始化失败时，请使用 [init]。
     *
     * @return Number of loaded routes. 已加载的路由数量。
     */
    @JvmStatic
    fun initOrThrow(): Int =
        when (val result = init()) {
            is InitializationResult.Success -> result.routeCount
            is InitializationResult.AlreadyInitialized -> result.routeCount
            is InitializationResult.Failure -> throw IllegalStateException(
                "Failed to initialize Lodestar routes.",
                result.cause
            )
        }

    /**
     * Navigates to the Activity matching [route]. Query and fragment do not participate in lookup,
     * but the original URI is preserved as `Intent.data` for the destination.
     * 导航到与 [route] 匹配的 Activity。query 和 fragment 不参与路由匹配，
     * 但原始 URI 会作为 `Intent.data` 保留给目标页使用。
     *
     * `FLAG_ACTIVITY_NEW_TASK` is added automatically when [context] is not an Activity.
     * 当 [context] 不是 Activity 时会自动添加 `FLAG_ACTIVITY_NEW_TASK`。
     *
     * @param configureIntent Configures extras, flags, and other Intent options. 在启动前配置 extras、flags 等。
     * @return A structured result that callers can handle. 可由调用方处理的结构化导航结果。
     */
    @JvmStatic
    @JvmOverloads
    fun navigate(
        context: Context,
        route: String,
        configureIntent: (Intent.() -> Unit)? = null
    ): NavigateResult {
        val snapshot = routes ?: return NavigateResult.NotInitialized
        val normalizedRoute = RouteNormalizer.normalize(route)
            ?: return NavigateResult.InvalidRoute(route)
        val target = snapshot[normalizedRoute]
            ?: return NavigateResult.RouteNotFound(normalizedRoute)

        return try {
            val options = navigateIntentOptions(context is Activity, route)
            val intent = Intent(context, target).apply {
                data = Uri.parse(options.dataUri)
                if (options.addNewTaskFlag) addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                configureIntent?.invoke(this)
            }
            context.startActivity(intent)
            NavigateResult.Success(normalizedRoute, target)
        } catch (cause: Throwable) {
            logger.error("Failed to navigate to '$normalizedRoute'.", cause)
            NavigateResult.LaunchFailed(normalizedRoute, cause)
        }
    }

    internal fun navigateIntentOptions(isActivityContext: Boolean, route: String): NavigateIntentOptions =
        NavigateIntentOptions(dataUri = route, addNewTaskFlag = !isActivityContext)

    internal fun resetForTesting() {
        synchronized(initializationLock) {
            routes = null
            logger = LodestarLogger.NONE
        }
    }
}

/**
 * Navigates from any [Context] using Lodestar.
 * 从任意 [Context] 使用 Lodestar 发起导航。
 */
fun Context.navigateTo(
    route: String,
    configureIntent: (Intent.() -> Unit)? = null
): NavigateResult = Lodestar.navigate(this, route, configureIntent)

internal data class NavigateIntentOptions(
    val dataUri: String,
    val addNewTaskFlag: Boolean
)

/** Initialization outcome. 初始化状态。 */
sealed interface InitializationResult {
    val routeCount: Int?

    /** Routes were loaded successfully. 路由加载成功。 */
    data class Success(override val routeCount: Int) : InitializationResult

    /** Initialization had already completed successfully. 初始化此前已成功完成。 */
    data class AlreadyInitialized(override val routeCount: Int) : InitializationResult

    /** No route table was published because initialization failed. 初始化失败，未发布任何路由表。 */
    data class Failure(val cause: Throwable) : InitializationResult {
        override val routeCount: Int? = null
    }
}

/** Navigate result; expected failures are returned explicitly. 导航结果；所有预期失败均通过返回值表达。 */
sealed interface NavigateResult {
    /** The target Activity was started. 目标 Activity 已启动。 */
    data class Success(val route: String, val target: Class<out Activity>) : NavigateResult

    /** [Lodestar.init] must complete before navigating. 导航前必须先成功执行 [Lodestar.init]。 */
    data object NotInitialized : NavigateResult

    /** The supplied URI cannot be normalized into a route key. 输入 URI 无法规范化为路由键。 */
    data class InvalidRoute(val route: String) : NavigateResult

    /** No destination is registered for the normalized route. 规范化路由没有对应目标。 */
    data class RouteNotFound(val route: String) : NavigateResult

    /** Android rejected or failed to launch the target Activity. Android 拒绝或未能启动目标 Activity。 */
    data class LaunchFailed(val route: String, val cause: Throwable) : NavigateResult
}

/**
 * Logging abstraction that keeps the runtime independent of a concrete logging framework.
 * Lodestar 日志抽象，避免 Runtime 强依赖具体日志框架。
 */
fun interface LodestarLogger {
    /** Receives a structured log event. 接收结构化日志事件。 */
    fun log(level: Level, message: String, cause: Throwable?)

    fun info(message: String) = log(Level.INFO, message, null)
    fun error(message: String, cause: Throwable) = log(Level.ERROR, message, cause)

    enum class Level { INFO, ERROR }

    companion object {
        @JvmField
        val NONE = LodestarLogger { _, _, _ -> }
    }
}
