package com.oayilix.lodestar.gradle

import org.gradle.api.GradleException
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassVisitor
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes
import java.util.SortedSet
import java.util.TreeMap
import java.util.TreeSet

/**
 * Discovers generated registries and rejects duplicate routes while visiting class bytecode.
 * 在遍历 class 字节码时发现生成的路由表，并拒绝重复路由。
 */
internal class LodestarMappingCollector {

    private val registryNames = TreeSet<String>()
    private val routeOwners = TreeMap<String, String>()

    fun registryNames(): SortedSet<String> = registryNames

    fun collect(entryName: String, bytecode: ByteArray) {
        val normalizedName = entryName.replace('\\', '/')
        if (!normalizedName.startsWith(REGISTRY_PACKAGE) ||
            !normalizedName.substringAfterLast('/').startsWith(REGISTRY_PREFIX) ||
            !normalizedName.endsWith(CLASS_SUFFIX)
        ) {
            return
        }

        val registryName = normalizedName.removeSuffix(CLASS_SUFFIX)
        registryNames += registryName

        // Generated registry methods encode each normalized route as a String LDC immediately
        // before inserting the Activity class literal into the map.
        // 生成的路由表方法通过 String LDC 写入规范化路由，随后把 Activity 类引用放入 Map。
        ClassReader(bytecode).accept(object : ClassVisitor(Opcodes.ASM9) {
            override fun visitMethod(
                access: Int,
                name: String?,
                descriptor: String?,
                signature: String?,
                exceptions: Array<out String>?
            ): MethodVisitor? {
                if (name != "get" || descriptor != "()Ljava/util/Map;") return null

                return object : MethodVisitor(Opcodes.ASM9) {
                    override fun visitLdcInsn(value: Any?) {
                        if (value is String && value.contains("://")) {
                            val previousOwner = routeOwners.putIfAbsent(value, registryName)
                            if (previousOwner != null && previousOwner != registryName) {
                                throw GradleException(
                                    "Duplicate Lodestar route '$value' generated by " +
                                        "'$previousOwner' and '$registryName'."
                                )
                            }
                        }
                    }
                }
            }
        }, ClassReader.SKIP_DEBUG or ClassReader.SKIP_FRAMES)
    }

    private companion object {
        const val REGISTRY_PACKAGE = "com/oayilix/lodestar/mapping/"
        const val REGISTRY_PREFIX = "LodestarRegistry_"
        const val CLASS_SUFFIX = ".class"
    }
}
